unify docker and local e2e jobs

diff --git a/.github/workflows/reusable__e2e-testing.yml b/.github/workflows/reusable__e2e-testing.yml
--- a/.github/workflows/reusable__e2e-testing.yml
+++ b/.github/workflows/reusable__e2e-testing.yml
@@ -48,10 +48,69 @@ jobs:
           fi
           echo "file_list=$FILES" >> $GITHUB_OUTPUT
 
-  # Job to run tests in parallel based on the discovered files
-  e2e-docker:
+#  # Job to run tests in parallel based on the discovered files
+#  e2e-docker:
+#    needs: get-e2e-files
+#    if: needs.get-e2e-files.outputs.file_list != '[]' && inputs.DOCKER_IMAGE_TAG != ''
+#    runs-on: ubuntu-latest # Or ubuntu-24.04
+#    strategy:
+#      fail-fast: false # Continue running other tests even if one fails
+#      matrix:
+#        file: ${{ fromJSON(needs.get-e2e-files.outputs.file_list) }}
+#    env:
+#      IMAGE_FILE_NAME: okr-docker-image.tar
+#
+#    steps:
+#      - run: echo "${{ github.run_id }}"
+#      - name: Checkout Target Repo Code (for Cypress config/plugins)
+#        uses: actions/checkout@v4
+#
+#      - name: Download Docker image artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: okr-image
+#          path: ${{ runner.temp }}
+#
+#      - name: Load image into Docker
+#        run: docker load --input ${{ runner.temp }}/okr-docker-image.tar
+#
+#      # --- E2E Test Execution Steps (Adjust as needed) ---
+#      - name: Set up Docker Compose / Start Services (if needed)
+#        run: cd docker && docker compose up -d keycloak-pitc
+#
+#      - name: Run Application Container
+#        run: |
+#          docker run --network=host \
+#          -e SPRING_PROFILES_ACTIVE=integration-test \
+#          ${{inputs.DOCKER_IMAGE_TAG }} &
+#
+#      - name: Set up node for Cypress
+#        uses: actions/setup-node@v4
+#        with:
+#          node-version: ${{vars.NODE_VERSION}}
+#
+#      - name: Cypress run e2e tests
+#        uses: cypress-io/github-action@v6
+#        with:
+#          build: npm i -D cypress
+#          working-directory: frontend
+#          install: false
+#          wait-on: 'http://pitc.okr.localhost:8080/config, http://localhost:8544'
+#          wait-on-timeout: 120
+#          browser: chrome
+#          headed: false
+#          config: baseUrl=http://pitc.okr.localhost:8080
+#          spec: cypress/e2e/${{ matrix.file }}
+#
+#      - uses: actions/upload-artifact@v4
+#        if: always()
+#        with:
+#          name: cypress-screenshots for ${{ matrix.file }}
+#          path: frontend/cypress/screenshots
+
+  e2e:
     needs: get-e2e-files
-    if: needs.get-e2e-files.outputs.file_list != '[]' && inputs.DOCKER_IMAGE_TAG != ''
+#    if: needs.get-e2e-files.outputs.file_list != '[]' && inputs.COMMIT_HASH != ''
     runs-on: ubuntu-latest # Or ubuntu-24.04
     strategy:
       fail-fast: false # Continue running other tests even if one fails
@@ -59,78 +118,39 @@ jobs:
         file: ${{ fromJSON(needs.get-e2e-files.outputs.file_list) }}
     env:
       IMAGE_FILE_NAME: okr-docker-image.tar
+      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
+      COMMIT_REF: ${{ inputs.COMMIT_HASH || (github.head_ref || github.ref_name) }}
 
     steps:
-      - run: echo "${{ github.run_id }}"
       - name: Checkout Target Repo Code (for Cypress config/plugins)
         uses: actions/checkout@v4
+        with:
+          ref: ${{ env.COMMIT_REF }}
+
+      - name: Set up Docker Compose / Start Services (if needed)
+        run: cd docker && docker compose up -d keycloak-pitc
 
       - name: Download Docker image artifact
+        if: inputs.DOCKER_IMAGE_TAG != ''
         uses: actions/download-artifact@v4
         with:
           name: okr-image
           path: ${{ runner.temp }}
 
       - name: Load image into Docker
+        if: inputs.DOCKER_IMAGE_TAG != ''
         run: docker load --input ${{ runner.temp }}/okr-docker-image.tar
 
-      # --- E2E Test Execution Steps (Adjust as needed) ---
-      - name: Set up Docker Compose / Start Services (if needed)
-        run: cd docker && docker compose up -d keycloak-pitc
-
-      - name: Run Application Container
+      - name: Run Application Container from image
+        if: inputs.DOCKER_IMAGE_TAG != ''
         run: |
           docker run --network=host \
           -e SPRING_PROFILES_ACTIVE=integration-test \
           ${{inputs.DOCKER_IMAGE_TAG }} &
-
-      - name: Set up node for Cypress
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{vars.NODE_VERSION}}
-
-      - name: Cypress run e2e tests
-        uses: cypress-io/github-action@v6
-        with:
-          build: npm i -D cypress
-          working-directory: frontend
-          install: false
-          wait-on: 'http://pitc.okr.localhost:8080/config, http://localhost:8544'
-          wait-on-timeout: 120
-          browser: chrome
-          headed: false
-          config: baseUrl=http://pitc.okr.localhost:8080
-          spec: cypress/e2e/${{ matrix.file }}
-
-      - uses: actions/upload-artifact@v4
-        if: always()
-        with:
-          name: cypress-screenshots for ${{ matrix.file }}
-          path: frontend/cypress/screenshots
-
-  e2e-local:
-    needs: get-e2e-files
-    if: needs.get-e2e-files.outputs.file_list != '[]' && inputs.COMMIT_HASH != ''
-    runs-on: ubuntu-latest # Or ubuntu-24.04
-    strategy:
-      fail-fast: false # Continue running other tests even if one fails
-      matrix:
-        file: ${{ fromJSON(needs.get-e2e-files.outputs.file_list) }}
-    env:
-      IMAGE_FILE_NAME: okr-docker-image.tar
-
-    steps:
-      - name: Checkout Target Repo Code (for Cypress config/plugins)
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ inputs.COMMIT_HASH }}
-
-      - name: Set up Docker Compose / Start Services (if needed)
-        run: cd docker && docker compose up -d keycloak-pitc
-
-      - name: Run application
+          
+      - name: Run application from local code
+        if: inputs.COMMIT_HASH != ''
         run: cd ./backend && mvn spring-boot:run -Dspring-boot.run.profiles=integration-test &
-
 
       - name: Set up node for Cypress
         uses: actions/setup-node@v4
