refactor version gen workflow

diff --git a/.github/workflows/reusable__generate-version.yml b/.github/workflows/reusable__generate-version.yml
--- a/.github/workflows/reusable__generate-version.yml
+++ b/.github/workflows/reusable__generate-version.yml
@@ -4,9 +4,13 @@ name: 'Reusable - Generate Version'
 on:
   workflow_call:
     inputs:
-      version_strategy_or_hash:
-        description: 'Major, Minor, Patch or commit hash '
-        required: true
+      RELEASE_TYPE:
+        description: 'Major, Minor, Patch'
+        required: false
+        type: string
+      COMMIT_HASH:
+        description: 'The commit hash to be used for the release'
+        required: false
         type: string
 
     outputs:
@@ -39,11 +43,15 @@ jobs:
     env:
       BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
     steps:
+      - name: Validate only one property is set
+        run: |
+          [[ $(( ${RELEASE_TYPE:++1} + ${COMMIT_HASH:++1} )) -eq 1 ]] || { echo "Error: Exactly one of RELEASE_TYPE or COMMIT_HASH must be set." >&2; exit 1; }
+               
       - name: Checkout
         uses: actions/checkout@v4
       - name: Stores the commit hash as environment variable
         run: |
-          commit_hash=$(./scripts/get-commit.sh ${{ env.BRANCH_NAME }} ${{ github.event.inputs.commit_hash }})
+          commit_hash=$(./scripts/get-commit.sh ${{ env.BRANCH_NAME }} ${{ inputs.COMMIT_HASH }})
           echo "Commit is set to \"$commit_hash\""
           echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV
           echo "SHORT_COMMIT_HASH=$(git rev-parse --short $commit_hash)" >> $GITHUB_ENV
@@ -56,7 +64,7 @@ jobs:
   update-version:
     runs-on: ubuntu-24.04
     needs: find-commit
-    if: github.event.inputs.deployment_type != 'Release from Commit'
+    if: inputs.RELEASE_TYPE != ''
     env:
       BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
     steps:
@@ -66,7 +74,7 @@ jobs:
           ref: ${{env.BRANCH_NAME}}
 
       - name: Update version
-        run: ./scripts/update-mvn-version.sh "${{ github.event.inputs.deployment_type }}"
+        run: ./scripts/update-mvn-version.sh "${{ inputs.RELEASE_TYPE }}"
 
       - name: Commit and Push Changes
         shell: bash
